tmp[0] -= sign * Trace(cgs * S_exp_4);
tmp[1] += sign * Trace(cgs * S_exp_7) * Trace(S_exp_8);
tmp[2] += sign * Trace(cgs * S_exp_9) * Trace(S_exp_12);

tmp[4] -= sign * Trace(cgs * S_exp_16);

tmp[6] -= sign * Trace(cgs * S_exp_21);
tmp[7] -= sign * Trace(cgs * S_exp_25);
tmp[8] += sign * Trace(cgs * S_exp_9) * Trace(S_exp_27);
tmp[9] += sign * Trace(cgs * S_exp_9) * Trace(S_exp_30);
tmp[10] -= sign * Trace(cgs * S_exp_33);
tmp[11] -= sign * Trace(cgs * S_exp_36);
tmp[12] -= sign * Trace(cgs * S_exp_41);


tmp[15] -= sign * Trace(cgs * S_exp_46);
































tmp[48] -= sign * Trace(cgs * S_exp_50);
tmp[49] -= sign * Trace(cgs * S_exp_53);
tmp[50] -= sign * Trace(cgs * S_exp_58);

tmp[52] -= sign * Trace(cgs * S_exp_60);



tmp[56] -= sign * Trace(cgs * S_exp_64);
tmp[57] -= sign * Trace(cgs * S_exp_68);
tmp[58] -= sign * Trace(cgs * S_exp_70);
tmp[59] -= sign * Trace(cgs * S_exp_72);


tmp[62] -= sign * Trace(cgs * S_exp_77);
tmp[63] += sign * Trace(cgs * S_exp_78) * Trace(S_exp_81);
tmp[64] += sign * Trace(cgs * S_exp_82) * Trace(S_exp_83);



tmp[68] -= sign * Trace(cgs * S_exp_85);

tmp[70] += sign * Trace(cgs * S_exp_86) * Trace(S_exp_83);

























tmp[96] -= sign * Trace(cgs * S_exp_88);
tmp[97] += sign * Trace(cgs * S_exp_89) * Trace(S_exp_91);
tmp[98] -= sign * Trace(cgs * S_exp_93);

tmp[100] += sign * Trace(cgs * S_exp_89) * Trace(S_exp_96);



tmp[104] -= sign * Trace(cgs * S_exp_98);
tmp[105] += sign * Trace(cgs * S_exp_99) * Trace(S_exp_100);
tmp[106] += sign * Trace(cgs * S_exp_89) * Trace(S_exp_102);
tmp[107] -= sign * Trace(cgs * S_exp_105);


tmp[110] -= sign * Trace(cgs * S_exp_107);
tmp[111] -= sign * Trace(cgs * S_exp_112);

tmp[113] -= sign * Trace(cgs * S_exp_115);


tmp[116] += sign * Trace(cgs * S_exp_89) * Trace(S_exp_117);
tmp[117] -= sign * Trace(cgs * S_exp_122);

tmp[119] += sign * Trace(cgs * S_exp_99) * Trace(S_exp_123);
























tmp[144] += sign * Trace(S_exp_124) * Trace(cgs * S_exp_127);
tmp[145] -= sign * Trace(S_exp_132);
tmp[146] -= sign * Trace(S_exp_136);

tmp[148] += sign * Trace(S_exp_138) * Trace(cgs * S_exp_139);

tmp[150] -= sign * Trace(S_exp_144);
tmp[151] -= sign * Trace(S_exp_148);
tmp[152] -= sign * Trace(S_exp_150);
tmp[153] -= sign * Trace(S_exp_154);
tmp[154] += sign * Trace(S_exp_155) * Trace(cgs * S_exp_139);
tmp[155] += sign * Trace(S_exp_156) * Trace(cgs * S_exp_139);
tmp[156] -= sign * Trace(S_exp_161);


tmp[159] -= sign * Trace(S_exp_166);
































tmp[192] += sign * Trace(S_exp_124) * Trace(S_exp_169);
tmp[193] -= sign * Trace(S_exp_172);
tmp[194] -= sign * Trace(S_exp_176);

tmp[196] += sign * Trace(S_exp_138) * Trace(S_exp_177);



tmp[200] -= sign * Trace(S_exp_179);
tmp[201] -= sign * Trace(S_exp_183);
tmp[202] += sign * Trace(S_exp_155) * Trace(S_exp_177);
tmp[203] += sign * Trace(S_exp_156) * Trace(S_exp_177);


tmp[206] += sign * Trace(S_exp_184) * Trace(S_exp_169);
tmp[207] -= sign * Trace(S_exp_189);
tmp[208] -= sign * Trace(S_exp_184) * Trace(S_exp_177) * Trace(S_exp_83);



tmp[212] -= sign * Trace(S_exp_191);
tmp[213] -= sign * Trace(S_exp_196);
tmp[214] += sign * Trace(S_exp_198) * Trace(S_exp_83);

























tmp[240] += sign * Trace(S_exp_124) * Trace(S_exp_201);
tmp[241] -= sign * Trace(S_exp_205);
tmp[242] -= sign * Trace(S_exp_209);

tmp[244] -= sign * Trace(S_exp_212);



tmp[248] -= sign * Trace(S_exp_214);
tmp[249] += sign * Trace(S_exp_215) * Trace(S_exp_100);
tmp[250] -= sign * Trace(S_exp_217);
tmp[251] -= sign * Trace(S_exp_221);


tmp[254] += sign * Trace(S_exp_184) * Trace(S_exp_201);
tmp[255] -= sign * Trace(S_exp_226);

tmp[257] -= sign * Trace(S_exp_230);


tmp[260] -= sign * Trace(S_exp_231);
tmp[261] -= sign * Trace(S_exp_236);

tmp[263] += sign * Trace(S_exp_215) * Trace(S_exp_123);
























































































































































































































































































































